name: Bug Report
description: Create a report to help us improve
title: '[Bug]: '
labels: ['type: bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Using this template makes it a lot easier for us to diagnose your problem, so please fill in as many fields as possible.

  - type: textarea
    id: description
    attributes:
      label: Summary
      description: A short description of the problem
      placeholder: |
        Include what you expected to happen, and what actually happened.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: input
    id: link-to-reproduction
    attributes:
      label: A link to a reproduction repository
      description:
        The fastest way to describe your bug is to provide a reproduction
        repository.
      placeholder: https://github.com/project/link-to-your-reproduction-repo

  - type: input
    id: plugin-version
    attributes:
      label: Plugin version
      description:
        The version of `@netlify/plugin-gatsby` that you are using. (This is in
        the build logs)
      placeholder: x.x.x
    validations:
      required: true

  - type: checkboxes
    id: more-info
    attributes:
      label: More information about your build
      options:
        - label: I am building using the CLI
        - label: I am building using file-based configuration (`netlify.toml`)
  - type: dropdown
    id: which-os
    attributes:
      label: What OS are you using?
      description: (If you're using the CLI) What OS are you using?
      options:
        - Windows
        - Mac OS
        - Linux
        - Other
  - type: textarea
    id: netlify-toml
    attributes:
      label: Your netlify.toml file
      description:
        (If you're using file-based config) Please provide a copy of your
        `netlify.toml` file.
      value: |
        <details>
          <summary>`netlify.toml`</summary>
          
        ```toml
        # Paste content of your `netlify.toml` file here
        ```

        </details>

  - type: textarea
    id: gatsby-config
    attributes:
      label: Configuration
      description:
        Please provide command line options and/or configuration file, if any.
      value: |
        <details>
          <summary>`gatsby-config.js` and options</summary>
          
        ```
        # Paste content of your `gatsby-config.js` file, and/or command line options here. Check there is no private info in there.
        ```

        </details>
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Enter the following command in a terminal and copy/paste its output:

        ```bash
        npx envinfo --system --binaries --browsers --npmPackages @netlify/plugin-gatsby
        ```
      value: |
        <details>
          <summary>Environment</summary>
          
        ```
        # Paste output from `npx envinfo` here.
        ```

        </details>

  - type: textarea
    id: gatsby-info
    attributes:
      label: Gatsby info
      description: |
        Enter the following command in a terminal and copy/paste its output:

        ```bash
        gatsby info
        ```
      value: |
        <details>
          <summary>gatsby info</summary>
          
        ```
        # Paste output from `gatsby info` here.
        ```

        </details>

  - type: textarea
    id: redirects-file
    attributes:
      label: Your _redirects file
      description:
        Please provide a copy of your `_redirects` file if you have one.
      value: |
        <details>
          <summary>`_redirects`</summary>
          
        ```toml
        # Paste content of your `_redirects` file here
        ```

        </details>

  - type: textarea
    id: build-logs
    attributes:
      label: Builds logs (or link to your logs)
      value: |
        <details>
          <summary>Build logs</summary>
          
        ```
        # Paste logs here
        ```

        </details>

  - type: textarea
    id: function-logs
    attributes:
      label: Function logs
      description:
        If it is a runtime error with DSG, SSR or API pages, please provide a
        copy of the relevant function log logs.
      value: |
        <details>
          <summary>Function logs</summary>
          
        ```
        # Paste logs here
        ```

        </details>
