[build]
command = "npm run build"
publish = "public/"
environment = { GATSBY_CLOUD_IMAGE_CDN = "true" }
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ../plugin/ || git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[[plugins]]
package = "../plugin/src/index.ts"

[[plugins]]
package = "@netlify/plugin-local-install-core"
