name: Plugin Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest] #, windows-latest] # TODO add an e2etest.bat file
        node-version: ['*']
        exclude:
          - os: macOS-latest
            node-version: 14.15.0
          # - os: windows-latest
          #   node-version: 14.15.0
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: '*'

      - name: Global Node packages cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key:
            ${{ matrix.os }}-build-${{ env.cache-name }}-${{
            hashFiles('**/package-lock.json') }} ${{ matrix.os }}-build-${{
            env.cache-name }}- ${{ matrix.os }}-build- ${{ matrix.os }}-

      - name: Test fixture dependency cache
        uses: actions/cache@v3
        with:
          path: plugin/test/fixtures/**/node_modules
          key:
            ${{ matrix.os }}-build-${{ env.cache-name }}-${{
            hashFiles('plugin/test/fixtures/**/package.json') }}-node-modules
          restore-keys: |
            ${{ matrix.os }}-build-${{ env.cache-name }}-${{ 
              hashFiles('plugin/test/fixtures/**/package.json') }}

      - run: npm install -g netlify-cli
      - run: npm ci
      - run: cd plugin && npm ci && npm run build
      - run: npm test
